# -*- python -*-
#
# Copyright (c) 2016 Stefan Seefeld
# All rights reserved.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

language: cpp

env:
- PYTHON=python
- PYTHON=python3

compiler:
  - gcc

before_install:
  - sudo apt-get install -y python-dev python-pip
  - sudo pip install future
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y libboost-all-dev

script: scons config --python=$PYTHON && scons && scons test

