# -*- python -*-
#
# Copyright (c) 2016 Stefan Seefeld
# All rights reserved.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

language: cpp

env:
- PYTHON=python CCFLAGS=-std=c++98
- PYTHON=python CCFLAGS=-std=c++11
- PYTHON=python3 CCFLAGS=-std=c++98
- PYTHON=python3 CCFLAGS=-std=c++11

compiler:
- gcc


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - python-dev python-pip
    - python3-dev
    - libboost-all-dev
    
before_install:
  - sudo pip install future

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: scons config --python=$PYTHON && scons && scons test

